/**
 * Deterministic weather-series evidence.
 *
 * Regenerated by `npm run weather:series` into
 * `evidence/weather/series-baseline.json`. One `WeatherField` at the opening
 * voyage's position and instant, on the shared default seed, sampled every six
 * world minutes for seventy-two world hours — three days of weather, which is
 * 2.4 real hours at the 30× calendar.
 *
 * The committed record is the proof that the generator is reproducible, that
 * every field stays inside the bounds `WeatherState` documents, that the wind's
 * bearing is continuous through north, and — the one that matters — that a
 * falling glass brings wind rather than merely sharing a seed with it.
 * `tests/weather.test.ts` recomputes the whole trace from scratch and requires
 * exact equality, so the record cannot drift from the code that claims to
 * produce it.
 */

import { findSeaState } from '../ocean/presets';
import {
  OPENING_LATITUDE_DEG,
  OPENING_LONGITUDE_DEG,
  OPENING_UTC_SECONDS,
} from '../world/openingVoyage';
import { vec3 } from '../world/math';
import { geodeticToEcef } from '../world/wgs84';
import {
  PRESSURE_SWING_HPA,
  STEERING_SPEED_MPS,
  WEATHER_DEFAULT_SEED,
  WeatherField,
  type WeatherBaseWind,
} from './WeatherField';
import { barometerReadingOf, neutralWeatherState } from './WeatherSystem';
import {
  HPA_PER_INCH_OF_MERCURY,
  STANDARD_PRESSURE_HPA,
  WEATHER_BOUNDS,
  assertWeatherStateWithinBounds,
  compassDeltaDeg,
  glassTendency,
} from './WeatherState';

/** The sea preset whose wind is the prevailing wind the field departs from. */
export const WEATHER_EVIDENCE_PRESET = 'CURRENT_MODERATE';

const DEG_TO_RAD = Math.PI / 180;

export const WEATHER_EVIDENCE_CONTRACT = Object.freeze({
  seed: WEATHER_DEFAULT_SEED,
  preset: WEATHER_EVIDENCE_PRESET,
  anchorLatitudeDeg: OPENING_LATITUDE_DEG,
  anchorLongitudeDeg: OPENING_LONGITUDE_DEG,
  anchorUtcSeconds: OPENING_UTC_SECONDS,
  durationWorldHours: 72,
  sampleIntervalWorldSeconds: 360,
  pressureSwingHpa: PRESSURE_SWING_HPA,
  steeringSpeedMps: STEERING_SPEED_MPS,
  standardPressureHpa: STANDARD_PRESSURE_HPA,
  hpaPerInchOfMercury: HPA_PER_INCH_OF_MERCURY,
  /**
   * The ship is held at the anchor position for the whole trace. Weather is a
   * function of place as well as time, but at the honest 1× voyage rate she
   * covers about 52 km in seventy-two world hours against synoptic wavelengths
   * of 1200 km and up, so holding her still isolates the time axis without
   * hiding anything the position axis would have shown.
   */
  stationary: true,
  conventions:
    'pressure in hPa, negative trend is a falling glass; windDirectionDeg is ' +
    'the compass heading the wind blows toward, matching WorldWind and the ' +
    'sea state',
} as const);

export interface WeatherTraceSample {
  worldHours: number;
  pressureHpa: number;
  inchesOfMercury: number;
  pressureTrendHpaPer3h: number;
  tendency: string;
  windSpeedMps: number;
  windDirectionDeg: number;
  cloudCoverThreshold: number;
  cloudCeilingM: number;
  precipRateMmPerHour: number;
  visibilityM: number;
}

export interface WeatherEvidenceStats {
  minPressureHpa: number;
  maxPressureHpa: number;
  minTrendHpaPer3h: number;
  maxTrendHpaPer3h: number;
  minWindSpeedMps: number;
  maxWindSpeedMps: number;
  meanWindSpeedMps: number;
  maxAbsDirectionStepDeg: number;
  totalDirectionTravelDeg: number;
  minCloudCoverThreshold: number;
  maxPrecipRateMmPerHour: number;
  minVisibilityM: number;
  /** Pearson r between the tendency and the wind speed. Must be negative. */
  glassWindCorrelation: number;
  /** Samples that hit a documented bound. Informational, not a failure. */
  clampedWindSamples: number;
}

export interface WeatherEvidence {
  contract: typeof WEATHER_EVIDENCE_CONTRACT;
  anchor: {
    pressureHpa: number;
    gradientMagnitude: number;
    windSpeedMps: number;
    baseWind: WeatherBaseWind;
    /** The proof of the neutral state, recorded rather than described. */
    derivedWindMatchesBaseExactly: boolean;
    neutralWindMatchesBaseExactly: boolean;
  };
  field: {
    geostrophicBoundMps: number;
    windScaleMps: number;
    tendencyBoundHpaPer3h: number;
    pressureBoundHpa: number;
  };
  stats: WeatherEvidenceStats;
  trace: WeatherTraceSample[];
  /**
   * The derived sky and precipitation across the whole reachable pressure and
   * tendency range, so the bounds are exercised even when the voyage's own
   * three days happen to be quiet. Cover, visibility and precipitation now
   * have MVP presentation consumers; the sweep keeps their full input range
   * from rotting unnoticed.
   */
  regimeSweep: Array<{
    pressureHpa: number;
    trendHpaPer3h: number;
    cloudCoverThreshold: number;
    cloudType: string;
    cloudCeilingM: number;
    precipRateMmPerHour: number;
    visibilityM: number;
    electricalActivity: number;
  }>;
}

/**
 * Storage rounding, shared with the recompute test for exact comparison.
 *
 * The trailing `+ 0` is not decoration. A tendency of −1e−19 at the anchor
 * rounds to −0, `JSON.stringify` writes −0 as `0`, and the recompute test then
 * fails against a committed record it produced itself. Folding the sign here
 * means the file and the rebuild agree about a number that has no sign.
 */
export function roundWeatherValue(value: number): number {
  return Math.round(value * 1e6) / 1e6 + 0;
}

export function weatherEvidenceBaseWind(): WeatherBaseWind {
  const preset = findSeaState(WEATHER_EVIDENCE_PRESET);
  return {
    speedMps: preset.generatingWind.speedMps,
    directionDeg: preset.generatingWind.directionDeg,
    gustiness: preset.generatingWind.gustiness,
  };
}

export function weatherEvidenceField(): WeatherField {
  const position = vec3();
  geodeticToEcef(
    OPENING_LATITUDE_DEG * DEG_TO_RAD,
    OPENING_LONGITUDE_DEG * DEG_TO_RAD,
    0,
    position,
  );
  return new WeatherField(
    position,
    OPENING_UTC_SECONDS,
    WEATHER_EVIDENCE_CONTRACT.seed,
  );
}

export function buildWeatherEvidence(): WeatherEvidence {
  const contract = WEATHER_EVIDENCE_CONTRACT;
  const base = weatherEvidenceBaseWind();
  const field = weatherEvidenceField();
  const position = field.anchor.positionEcefM;

  const steps =
    (contract.durationWorldHours * 3600) / contract.sampleIntervalWorldSeconds;

  const trace: WeatherTraceSample[] = [];
  const trends: number[] = [];
  const speeds: number[] = [];

  let minPressure = Number.POSITIVE_INFINITY;
  let maxPressure = Number.NEGATIVE_INFINITY;
  let minTrend = Number.POSITIVE_INFINITY;
  let maxTrend = Number.NEGATIVE_INFINITY;
  let minSpeed = Number.POSITIVE_INFINITY;
  let maxSpeed = Number.NEGATIVE_INFINITY;
  let minCover = Number.POSITIVE_INFINITY;
  let maxPrecip = 0;
  let minVisibility = Number.POSITIVE_INFINITY;
  let maxAbsStep = 0;
  let totalTravel = 0;
  let clamped = 0;
  let previousDirection: number | undefined;

  for (let i = 0; i <= steps; i++) {
    const seconds = i * contract.sampleIntervalWorldSeconds;
    const state = field.derive(seconds, position, base);
    assertWeatherStateWithinBounds(state, `trace sample ${i}`);

    minPressure = Math.min(minPressure, state.pressureHpa);
    maxPressure = Math.max(maxPressure, state.pressureHpa);
    minTrend = Math.min(minTrend, state.pressureTrendHpaPer3h);
    maxTrend = Math.max(maxTrend, state.pressureTrendHpaPer3h);
    minSpeed = Math.min(minSpeed, state.windSpeedMps);
    maxSpeed = Math.max(maxSpeed, state.windSpeedMps);
    minCover = Math.min(minCover, state.cloudCoverThreshold);
    maxPrecip = Math.max(maxPrecip, state.precipRateMmPerHour);
    minVisibility = Math.min(minVisibility, state.visibilityM);
    if (state.windSpeedMps >= WEATHER_BOUNDS.windSpeedMps.max) clamped += 1;

    if (previousDirection !== undefined) {
      const step = compassDeltaDeg(previousDirection, state.windDirectionDeg);
      maxAbsStep = Math.max(maxAbsStep, Math.abs(step));
      totalTravel += Math.abs(step);
    }
    previousDirection = state.windDirectionDeg;

    trends.push(state.pressureTrendHpaPer3h);
    speeds.push(state.windSpeedMps);

    const reading = barometerReadingOf(state);
    trace.push({
      worldHours: roundWeatherValue(seconds / 3600),
      pressureHpa: roundWeatherValue(state.pressureHpa),
      inchesOfMercury: roundWeatherValue(reading.inchesOfMercury),
      pressureTrendHpaPer3h: roundWeatherValue(state.pressureTrendHpaPer3h),
      tendency: reading.tendency,
      windSpeedMps: roundWeatherValue(state.windSpeedMps),
      windDirectionDeg: roundWeatherValue(state.windDirectionDeg),
      cloudCoverThreshold: roundWeatherValue(state.cloudCoverThreshold),
      cloudCeilingM: roundWeatherValue(state.cloudCeilingM),
      precipRateMmPerHour: roundWeatherValue(state.precipRateMmPerHour),
      visibilityM: roundWeatherValue(state.visibilityM),
    });
  }

  const anchorState = field.derive(0, position, base);
  const neutral = neutralWeatherState(base);

  return {
    contract,
    anchor: {
      pressureHpa: roundWeatherValue(field.anchorPressureHpa),
      gradientMagnitude: roundWeatherValue(field.anchorGradient.magnitude),
      windSpeedMps: roundWeatherValue(field.anchorWind.speedMps),
      baseWind: { ...base },
      derivedWindMatchesBaseExactly:
        Object.is(anchorState.windSpeedMps, base.speedMps) &&
        Object.is(anchorState.windDirectionDeg, base.directionDeg) &&
        Object.is(anchorState.gustiness, base.gustiness),
      neutralWindMatchesBaseExactly:
        Object.is(neutral.windSpeedMps, base.speedMps) &&
        Object.is(neutral.windDirectionDeg, base.directionDeg) &&
        Object.is(neutral.gustiness, base.gustiness),
    },
    field: {
      geostrophicBoundMps: roundWeatherValue(field.geostrophicBoundMps),
      windScaleMps: roundWeatherValue(field.windScaleMps),
      tendencyBoundHpaPer3h: roundWeatherValue(field.tendencyBoundHpaPer3h),
      pressureBoundHpa: roundWeatherValue(field.pressureBoundHpa),
    },
    stats: {
      minPressureHpa: roundWeatherValue(minPressure),
      maxPressureHpa: roundWeatherValue(maxPressure),
      minTrendHpaPer3h: roundWeatherValue(minTrend),
      maxTrendHpaPer3h: roundWeatherValue(maxTrend),
      minWindSpeedMps: roundWeatherValue(minSpeed),
      maxWindSpeedMps: roundWeatherValue(maxSpeed),
      meanWindSpeedMps: roundWeatherValue(
        speeds.reduce((sum, value) => sum + value, 0) / speeds.length,
      ),
      maxAbsDirectionStepDeg: roundWeatherValue(maxAbsStep),
      totalDirectionTravelDeg: roundWeatherValue(totalTravel),
      minCloudCoverThreshold: roundWeatherValue(minCover),
      maxPrecipRateMmPerHour: roundWeatherValue(maxPrecip),
      minVisibilityM: roundWeatherValue(minVisibility),
      glassWindCorrelation: roundWeatherValue(correlation(trends, speeds)),
      clampedWindSamples: clamped,
    },
    trace,
    regimeSweep: buildRegimeSweep(field),
  };
}

/**
 * Walk the derived sky across the field's whole reachable range by sampling
 * the *derivation* at synthetic pressures and tendencies rather than waiting
 * for the voyage to produce them.
 */
function buildRegimeSweep(field: WeatherField): WeatherEvidence['regimeSweep'] {
  const sweep: WeatherEvidence['regimeSweep'] = [];
  for (let i = 0; i <= 10; i++) {
    const pressureHpa = STANDARD_PRESSURE_HPA + PRESSURE_SWING_HPA * (1 - (2 * i) / 10);
    const trendHpaPer3h = 4 - (8 * i) / 10;
    const derived = field.deriveSky(pressureHpa, trendHpaPer3h);
    sweep.push({
      pressureHpa: roundWeatherValue(pressureHpa),
      trendHpaPer3h: roundWeatherValue(trendHpaPer3h),
      cloudCoverThreshold: roundWeatherValue(derived.cloudCoverThreshold),
      cloudType: derived.cloudType,
      cloudCeilingM: roundWeatherValue(derived.cloudCeilingM),
      precipRateMmPerHour: roundWeatherValue(derived.precipRateMmPerHour),
      visibilityM: roundWeatherValue(derived.visibilityM),
      electricalActivity: roundWeatherValue(derived.electricalActivity),
    });
  }
  return sweep;
}

function correlation(a: readonly number[], b: readonly number[]): number {
  const n = a.length;
  const meanA = a.reduce((sum, value) => sum + value, 0) / n;
  const meanB = b.reduce((sum, value) => sum + value, 0) / n;
  let covariance = 0;
  let varianceA = 0;
  let varianceB = 0;
  for (let i = 0; i < n; i++) {
    const da = a[i] - meanA;
    const db = b[i] - meanB;
    covariance += da * db;
    varianceA += da * da;
    varianceB += db * db;
  }
  const denominator = Math.sqrt(varianceA * varianceB);
  return denominator === 0 ? 0 : covariance / denominator;
}

/**
 * Physical gates, shared verbatim by the exporter and the test suite.
 * Throws with a specific message on the first violated gate.
 */
export function validateWeatherEvidence(evidence: WeatherEvidence): void {
  const { anchor, stats, trace } = evidence;

  if (trace.length < 2) throw new Error('weather trace is empty');

  if (!anchor.derivedWindMatchesBaseExactly) {
    throw new Error(
      'the generated wind at the anchor is not bit-identical to the base wind — ' +
        'WX1 cannot claim a pixel-identical neutral state',
    );
  }
  if (!anchor.neutralWindMatchesBaseExactly) {
    throw new Error(
      'the neutral weather state does not reproduce the base wind exactly',
    );
  }

  for (const [index, sample] of trace.entries()) {
    const numbers = [
      sample.worldHours,
      sample.pressureHpa,
      sample.inchesOfMercury,
      sample.pressureTrendHpaPer3h,
      sample.windSpeedMps,
      sample.windDirectionDeg,
      sample.cloudCoverThreshold,
      sample.cloudCeilingM,
      sample.precipRateMmPerHour,
      sample.visibilityM,
    ];
    if (numbers.some((value) => !Number.isFinite(value))) {
      throw new Error(`trace sample ${index} contains a non-finite value`);
    }
    if (
      sample.windDirectionDeg < 0 ||
      sample.windDirectionDeg >= WEATHER_BOUNDS.windDirectionDeg.max
    ) {
      throw new Error(
        `trace sample ${index}: windDirectionDeg ${sample.windDirectionDeg} is not in [0, 360)`,
      );
    }
    // The barometer and the series must be one number, not two.
    const expectedInches = sample.pressureHpa / HPA_PER_INCH_OF_MERCURY;
    if (Math.abs(sample.inchesOfMercury - expectedInches) > 1e-5) {
      throw new Error(
        `trace sample ${index}: barometer reading ${sample.inchesOfMercury} inHg ` +
          `disagrees with the series pressure ${sample.pressureHpa} hPa`,
      );
    }
    if (sample.tendency !== glassTendency(sample.pressureTrendHpaPer3h)) {
      throw new Error(
        `trace sample ${index}: tendency word "${sample.tendency}" does not match ` +
          `a trend of ${sample.pressureTrendHpaPer3h} hPa/3h`,
      );
    }
  }

  const bounded: Array<[string, number, number, number]> = [
    ['pressure', stats.minPressureHpa, WEATHER_BOUNDS.pressureHpa.min, WEATHER_BOUNDS.pressureHpa.max],
    ['pressure', stats.maxPressureHpa, WEATHER_BOUNDS.pressureHpa.min, WEATHER_BOUNDS.pressureHpa.max],
    ['trend', stats.minTrendHpaPer3h, WEATHER_BOUNDS.pressureTrendHpaPer3h.min, WEATHER_BOUNDS.pressureTrendHpaPer3h.max],
    ['trend', stats.maxTrendHpaPer3h, WEATHER_BOUNDS.pressureTrendHpaPer3h.min, WEATHER_BOUNDS.pressureTrendHpaPer3h.max],
    ['wind speed', stats.minWindSpeedMps, WEATHER_BOUNDS.windSpeedMps.min, WEATHER_BOUNDS.windSpeedMps.max],
    ['wind speed', stats.maxWindSpeedMps, WEATHER_BOUNDS.windSpeedMps.min, WEATHER_BOUNDS.windSpeedMps.max],
    ['cover threshold', stats.minCloudCoverThreshold, WEATHER_BOUNDS.cloudCoverThreshold.min, WEATHER_BOUNDS.cloudCoverThreshold.max],
    ['precipitation', stats.maxPrecipRateMmPerHour, WEATHER_BOUNDS.precipRateMmPerHour.min, WEATHER_BOUNDS.precipRateMmPerHour.max],
    ['visibility', stats.minVisibilityM, WEATHER_BOUNDS.visibilityM.min, WEATHER_BOUNDS.visibilityM.max],
  ];
  for (const [name, value, min, max] of bounded) {
    if (value < min || value > max) {
      throw new Error(`${name} statistic ${value} is outside [${min}, ${max}]`);
    }
  }

  // The pressure must actually go somewhere, or the glass has nothing to lead.
  const pressureSpan = stats.maxPressureHpa - stats.minPressureHpa;
  if (pressureSpan < 6) {
    throw new Error(
      `the glass moved only ${pressureSpan.toFixed(2)} hPa in seventy-two hours; ` +
        'a barometer that never moves is the state this round exists to leave',
    );
  }

  // Continuity through north. A vector bearing cannot jump; a wrapped one can,
  // and this is the gate that would catch it.
  const worstStep = stats.maxAbsDirectionStepDeg;
  if (worstStep > 25) {
    throw new Error(
      `the wind veered ${worstStep.toFixed(1)}° between two six-minute samples; ` +
        'that is a discontinuity, most likely a compass wrap taken as a difference',
    );
  }

  // The whole point of deriving wind from pressure.
  if (!(stats.glassWindCorrelation < -0.3)) {
    throw new Error(
      `the glass and the wind correlate at r = ${stats.glassWindCorrelation}; ` +
        'a falling glass must bring wind, and below -0.3 is the agreed floor',
    );
  }
}
