/**
 * The canonical sea-state parameter model.
 *
 * A `SeaState` is a *physical description of a sea*, not a list of waves. It
 * says how hard the wind is blowing and for how long, what swell has arrived
 * from where, and how the water should break. `spectrum.ts` turns that into
 * Gerstner components; `WaveField` renders and samples them.
 *
 * DIRECTION CONVENTION — one convention, stated once
 * --------------------------------------------------
 * Every direction in this file is **the heading the waves or wind travel
 * towards**, in degrees clockwise from local north, expressed in the *current
 * local tangent presentation frame* that `WorldRenderAdapter` derives from
 * `PlanetaryWorld`'s transported frame. It is the same convention
 * `WindSystem.headingDeg` already uses, and it maps to a local render direction
 * as `(sin θ, −cos θ)`.
 *
 * This is a presentation heading, not a second position authority. Nothing here
 * integrates travel, and nothing here is written back into `PlanetaryWorld`.
 *
 * WIND VERSUS SWELL — the contract this round exists to establish
 * --------------------------------------------------------------
 * The local wind sea is *generated by* `generatingWind`: its height, period,
 * spread, peakedness and direction are all derived from wind speed, maturity
 * and wind heading. Turning the wind rotates it.
 *
 * Primary and secondary swell are *remote*. They carry their own headings and
 * are never touched by the wind controls. A swell that arrived from a storm two
 * thousand kilometres away does not swing round because the local breeze
 * backed, and neither does this one.
 *
 * `generatingWind` IS NOT "THE WIND" — read this before using it
 * --------------------------------------------------------------
 * Until WX2 this field was called `wind`, and because `WorldWind.setMean` was
 * fed from it every frame it really was the wind: one number meaning both "how
 * hard it is blowing now" and "what grew this sea". That made the most
 * characteristic thing weather does to water — the wind freshens and the sea
 * has not answered yet — literally inexpressible.
 *
 * The present wind now lives in `WeatherState` (`src/weather/WeatherState.ts`)
 * and is the only thing `WorldWind` is fed. This record is the *sea's* wind:
 * the wind that is generating the wind sea drawn here, together with how far
 * that sea has developed under it. **`speedMps` and `maturity` only mean
 * something together** — a young sea at 14 m/s and a mature sea at 8 m/s can
 * carry the same significant height, and while the wind is freshening that is
 * exactly the pair the sea holds. `src/ocean/WindSeaMemory.ts` writes them,
 * and states the one formula that relates them to the present wind.
 *
 * The numbers in `presets.ts` are unchanged by the rename, deliberately and to
 * the last bit: at a steady wind the generating wind IS the present wind, so
 * every preset still describes the same sea it described before.
 */

import type { Spectrum, WaveBand } from './spectrum';
import {
  buildSpectrum,
  effectiveGrowthWind,
  spreadExponentForDegrees,
  windSeaFromWind,
  windSeaGamma,
  windSeaSpreadExponent,
} from './spectrum';

/**
 * The wind that is generating this wind sea, and how far it has got.
 *
 * Not the present wind — see the header. The pair `(speedMps, maturity)` is
 * the whole description; neither half is meaningful alone.
 */
export interface GeneratingWindParams {
  /** Wind speed at the 10 m reference height, m/s. */
  speedMps: number;
  /** Heading the wind blows towards, degrees. See the direction convention. */
  directionDeg: number;
  /** 0..1. Modulates short-wave energy, streaking and spray in gusts. */
  gustiness: number;
  /**
   * 0..1 fetch/duration proxy. 1 is a fully developed sea for this wind speed;
   * low values give the short, steep, disorganised sea of a wind that has only
   * just risen.
   */
  maturity: number;
}

export interface SwellParams {
  enabled: boolean;
  /** Significant wave height of this system alone, metres. */
  significantHeight: number;
  /** Peak period, seconds. */
  peakPeriod: number;
  /** Heading the swell travels towards, degrees. */
  directionDeg: number;
  /** Circular directional spread, degrees. Small is organised and clean. */
  spreadDeg: number;
  /** 0..1 crest sharpness. Independent of height — see `WaveField`. */
  steepness: number;
  /** 0..1. Higher narrows the band, producing longer, stronger wave groups. */
  groupiness: number;
}

export interface RoughnessParams {
  /** 0..2 multiplier on the capillary/fine-detail layer. */
  fineRoughness: number;
  /** Metres of the largest detail octave. */
  detailScale: number;
  /**
   * Dimensionless gain on the *derived* detail amplitude, default 1.
   *
   * The base amplitude is `WaveField.detailAmplitude`, computed from the slope
   * variance the discrete components leave unresolved — so the texture tracks
   * the wind across every weather state. This field trims it artistically; it
   * is no longer an absolute slope amplitude.
   */
  detailStrength: number;
  /** 0..1 strength of wind-aligned gust streaks on the surface. */
  gustStreak: number;
  /**
   * 0..1: how far real *geometry* is allowed below the 3.5 m resolution floor.
   *
   * 0 keeps the classic floor (everything shorter is shading). 1 drops the
   * geometric floor to ~1.1 m and art-boosts the short wind-ladder rungs, so
   * the near field carries genuine metre-scale displaced chop — parallax and
   * silhouette, not just lit texture. Costs a handful of extra live
   * components; the raft is unaffected (sub-raft wavelengths average out
   * across its buoyancy stations), and the detail-noise amplitude re-derives
   * itself smaller automatically because the resolved band now carries more
   * of the slope budget.
   */
  microChop: number;
}

export interface WhitewaterParams {
  /** −1..+1 bias on the breaking threshold. Negative makes foam easier. */
  thresholdBias: number;
  /** 0..3 multiplier on foam injection rate. */
  generation: number;
  /** Seconds for foam to decay to 1/e. */
  persistenceSeconds: number;
  /** 0..1 extra breakup/fragmentation of ageing foam. */
  breakup: number;
  /** Fraction of the wind speed that drags surface foam downwind. */
  windAdvection: number;
  /** 0..2 multiplier on spindrift emission. */
  sprayIntensity: number;
}

/** Whether a sea belongs to gameplay or exists only as a diagnostic fixture. */
export type SeaStatePurpose = 'PLAYABLE' | 'DIAGNOSTIC';

export interface SeaState {
  readonly name: string;
  readonly label: string;
  /** Deterministic seed for component phases and directions. */
  readonly seed: number;
  /** The wind that grew this sea — **not** the wind now. See the header. */
  readonly generatingWind: GeneratingWindParams;
  readonly primary: SwellParams;
  readonly secondary: SwellParams;
  /**
   * 0..1 crest sharpness of the wind sea. Derived from maturity by default —
   * young seas are steep — but overridable per preset.
   */
  readonly windSeaSteepness: number;
  readonly roughness: RoughnessParams;
  readonly whitewater: WhitewaterParams;
  readonly purpose: SeaStatePurpose;
  /** True for states meant to be inspected with time stopped. */
  readonly frozen?: boolean;
  /**
   * Force a slot count for one or more systems. Only the diagnostic states use
   * this — a parity probe wants an exactly known number of components, not a
   * spectrum. Production presets leave it undefined and take the device budget.
   */
  readonly slotOverride?: Partial<SlotBudget>;
  readonly notes: string;
}

/**
 * Component-slot budget: 24 wind sea, 12 primary swell, 12 secondary swell.
 *
 * FIXED, AND THE SAME ON EVERY DEVICE. A per-device component count would make
 * the raft float differently on a phone than on a desktop — the CPU sampler and
 * the GPU would still agree with each other, so the parity probe would stay
 * green while the physics quietly diverged between devices. Mobile saves its
 * budget on mesh density, detail octaves, foam resolution and spray count, none
 * of which the raft can feel.
 *
 * The split is fixed rather than redistributed when a system is disabled,
 * because slot identity is what makes a smooth morph possible: bin `j` of the
 * primary swell must stay in the same slot whatever else changes, so its phase
 * can be carried across a parameter change instead of reset.
 *
 * Why these numbers:
 *
 * - 24 for the wind sea. Below 16 it reads as a few discrete wave trains rather
 *   than a confused sea; 24 is where it stops looking organised at all. Past 32
 *   the extra components buy nothing the fragment detail noise does not already
 *   supply, because with m₁ binning the top ten components already carry about
 *   70 % of the energy.
 * - 12 per swell, and deliberately not more. A swell partition is narrow-banded
 *   by construction, so its components sit close together in frequency; the
 *   slowest beat is roughly `N / Δf_total`, and over-populating a narrow band
 *   pushes that past the point where it reads as "the sea is frozen" rather
 *   than as sets. Below about 5 the group cycle becomes a metronome. Six to
 *   twelve is the window, and 12 is the top of it.
 */
export interface SlotBudget {
  wind: number;
  primary: number;
  secondary: number;
}

export const SLOTS_DEFAULT: SlotBudget = { wind: 24, primary: 12, secondary: 12 };

/** Total uniform slots reserved. Must be >= the sum of any budget above. */
export const MAX_WAVES = 48;

const DEG = Math.PI / 180;

export function defaultRoughness(): RoughnessParams {
  return { fineRoughness: 1, detailScale: 2.4, detailStrength: 1, gustStreak: 0.35, microChop: 0 };
}

export function defaultWhitewater(): WhitewaterParams {
  return {
    thresholdBias: 0,
    generation: 1,
    persistenceSeconds: 7,
    breakup: 0.5,
    windAdvection: 0.03,
    sprayIntensity: 1,
  };
}

export function noSwell(): SwellParams {
  return {
    enabled: false,
    significantHeight: 0,
    peakPeriod: 10,
    directionDeg: 0,
    spreadDeg: 14,
    steepness: 0.45,
    groupiness: 0.5,
  };
}

/**
 * Wind-sea crest sharpness from development.
 *
 * Steepness here is a *fraction of the full trochoidal crest sharpness* that
 * the sea can safely carry — 1 would be a Gerstner wave with circular particle
 * orbits, the physically correct limit. `WaveField` scales it by the largest
 * value that keeps folding several standard deviations out of reach, so the
 * control means the same thing in a 0.1 m sea and a 7 m one.
 *
 * A young sea is steep. That is the single most recognisable thing about wind
 * chop, and the reason it looks nothing like a scaled-down swell.
 */
export function windSeaSteepnessFor(maturity: number): number {
  const m = Math.min(Math.max(maturity, 0), 1);
  return 0.95 - 0.25 * m;
}

/**
 * Resolve a sea state into its Gerstner components.
 *
 * `frameHeadingDeg` rotates every heading in the state from the local tangent
 * presentation frame into the render frame's axes. It is supplied by the
 * caller from `WorldRenderAdapter`, so a course change moves the whole sea
 * coherently without any of these parameters being rewritten.
 */
export function resolveSeaState(
  state: SeaState,
  deviceBudget: SlotBudget,
  frameHeadingDeg = 0,
): Spectrum {
  const budget: SlotBudget = { ...deviceBudget, ...(state.slotOverride ?? {}) };
  // The growth laws see the saturated wind, never the raw one: beyond the
  // validity ceiling extra wind is presentation (spray, streaks, visibility),
  // not taller waves. See `effectiveGrowthWind`.
  const growthWind = effectiveGrowthWind(state.generatingWind.speedMps);
  const windSea = windSeaFromWind(growthWind, state.generatingWind.maturity);
  const heading = (deg: number): number => (deg + frameHeadingDeg) * DEG;

  const swellSystem = (
    swell: SwellParams,
    slots: number,
    seed: number,
    band: WaveBand,
  ) => ({
    // A disabled system stays in its slots at zero height rather than
    // disappearing, so enabling it is an amplitude ramp from zero — continuous
    // everywhere in space and time — instead of a set of components appearing
    // mid-frame with arbitrary phase.
    significantHeight: swell.enabled ? swell.significantHeight : 0,
    peakPeriod: swell.peakPeriod,
    headingRad: heading(swell.directionDeg),
    spreadExponent: spreadExponentForDegrees(swell.spreadDeg),
    gamma: 3.3,
    // Groupiness *is* the spectral bandwidth: for a narrow-band process the
    // envelope decorrelates on 1/sigma_f, so the number of waves in a set is
    // exactly fp/sigma_f. Mapping the control straight onto that means the sets
    // are as long as the control says, with no envelope function anywhere and
    // nothing extra for the CPU and GPU to agree about.
    groupWaves: 4.5 + 9.0 * Math.min(Math.max(swell.groupiness, 0), 1),
    groupiness: swell.groupiness,
    sharpness: swell.steepness,
    microChop: state.roughness.microChop,
    slots,
    seed,
    band,
  });

  const systems = [
    {
      significantHeight: windSea.significantHeight,
      peakPeriod: windSea.peakPeriod,
      headingRad: heading(state.generatingWind.directionDeg),
      spreadExponent: windSeaSpreadExponent(growthWind, windSea.peakPeriod),
      gamma: windSeaGamma(state.generatingWind.maturity),
      // No `groupWaves`: a wind sea uses the broad-band ladder layout. Its own
      // bandwidth is about 0.55 fp, far too wide for groups to be perceptible,
      // which is why chop looks busy rather than rhythmic. That is correct
      // physics, not a limitation — sets come from swell, never from chop.
      sharpness: state.windSeaSteepness,
      microChop: state.roughness.microChop,
      slots: budget.wind,
      seed: state.seed * 7919 + 11,
      band: 'wind' as WaveBand,
    },
    swellSystem(state.primary, budget.primary, state.seed * 6547 + 29, 'primary'),
    swellSystem(state.secondary, budget.secondary, state.seed * 5231 + 47, 'secondary'),
  ];

  return buildSpectrum({ systems });
}

/** Per-band crest sharpness, in the slot order `resolveSeaState` produces. */
export function bandSteepness(state: SeaState, band: WaveBand): number {
  if (band === 'wind') return state.windSeaSteepness;
  if (band === 'primary') return state.primary.steepness;
  return state.secondary.steepness;
}

// --- interpolation ----------------------------------------------------------

const lerp = (a: number, b: number, t: number): number => a + (b - a) * t;

/** Shortest-arc interpolation, so 350° -> 10° goes forwards through north. */
function lerpAngleDeg(a: number, b: number, t: number): number {
  let delta = ((b - a + 540) % 360) - 180;
  return a + delta * t;
}

function lerpSwell(a: SwellParams, b: SwellParams, t: number): SwellParams {
  return {
    // A system that is switching on fades up from zero height rather than
    // appearing, so `enabled` never causes a step.
    enabled: a.enabled || b.enabled,
    significantHeight: lerp(
      a.enabled ? a.significantHeight : 0,
      b.enabled ? b.significantHeight : 0,
      t,
    ),
    peakPeriod: lerp(a.peakPeriod, b.peakPeriod, t),
    directionDeg: lerpAngleDeg(a.directionDeg, b.directionDeg, t),
    spreadDeg: lerp(a.spreadDeg, b.spreadDeg, t),
    steepness: lerp(a.steepness, b.steepness, t),
    groupiness: lerp(a.groupiness, b.groupiness, t),
  };
}

/**
 * Interpolate two sea states.
 *
 * Every quantity here is continuous in `t`, including the headings. The seed is
 * taken from the destination at the halfway point; because component phase is
 * carried across parameter changes rather than rebuilt (see `WaveField`), the
 * seed change alters only which *future* components are drawn for a slot, not
 * the phase the slot is currently at.
 */
export function blendSeaState(a: SeaState, b: SeaState, t: number): SeaState {
  const u = Math.min(Math.max(t, 0), 1);
  // WX2 made transitions the normal state of affairs rather than a preset
  // button being pressed: the sea is now in transition whenever the weather is
  // moving, which is most of the time. A sea morphing between two developments
  // of ITSELF is not going anywhere, and labelling it `X->X` in every readout
  // and benchmark caption said otherwise.
  const morphing = u < 1 && a.name !== b.name;
  return {
    name: morphing ? `${a.name}->${b.name}` : b.name,
    label: morphing ? `${a.label} → ${b.label}` : b.label,
    seed: u < 0.5 ? a.seed : b.seed,
    generatingWind: {
      speedMps: lerp(a.generatingWind.speedMps, b.generatingWind.speedMps, u),
      directionDeg: lerpAngleDeg(
        a.generatingWind.directionDeg,
        b.generatingWind.directionDeg,
        u,
      ),
      gustiness: lerp(a.generatingWind.gustiness, b.generatingWind.gustiness, u),
      maturity: lerp(a.generatingWind.maturity, b.generatingWind.maturity, u),
    },
    primary: lerpSwell(a.primary, b.primary, u),
    secondary: lerpSwell(a.secondary, b.secondary, u),
    windSeaSteepness: lerp(a.windSeaSteepness, b.windSeaSteepness, u),
    roughness: {
      fineRoughness: lerp(a.roughness.fineRoughness, b.roughness.fineRoughness, u),
      detailScale: lerp(a.roughness.detailScale, b.roughness.detailScale, u),
      detailStrength: lerp(a.roughness.detailStrength, b.roughness.detailStrength, u),
      gustStreak: lerp(a.roughness.gustStreak, b.roughness.gustStreak, u),
      microChop: lerp(a.roughness.microChop, b.roughness.microChop, u),
    },
    whitewater: {
      thresholdBias: lerp(a.whitewater.thresholdBias, b.whitewater.thresholdBias, u),
      generation: lerp(a.whitewater.generation, b.whitewater.generation, u),
      persistenceSeconds: lerp(
        a.whitewater.persistenceSeconds,
        b.whitewater.persistenceSeconds,
        u,
      ),
      breakup: lerp(a.whitewater.breakup, b.whitewater.breakup, u),
      windAdvection: lerp(a.whitewater.windAdvection, b.whitewater.windAdvection, u),
      sprayIntensity: lerp(a.whitewater.sprayIntensity, b.whitewater.sprayIntensity, u),
    },
    purpose: u < 0.5 ? a.purpose : b.purpose,
    notes: morphing ? 'transition' : b.notes,
  };
}

/** Deep copy, so the lab can edit a state without mutating a preset. */
export function cloneSeaState(state: SeaState): SeaState {
  return {
    ...state,
    generatingWind: { ...state.generatingWind },
    primary: { ...state.primary },
    secondary: { ...state.secondary },
    roughness: { ...state.roughness },
    whitewater: { ...state.whitewater },
  };
}
