/**
 * Deterministic wind-sea memory evidence — WX2's two gates, as one file.
 *
 * Regenerated by `npm run weather:seatrace` into
 * `evidence/weather/wind-sea-baseline.json`. Two scripted runs of the whole
 * production path — `WindSeaCoupling` driving a real `SeaStateController`,
 * whose transitions a real `WaveField` follows with `applySeaState(state,
 * true)`, exactly as `ProductionSimulationRuntime` does it:
 *
 * - **freshening** — the wind gets up from the production sea's 6 m/s to a
 *   near-gale over five real minutes, and veers with it. The gate is that the
 *   wind-sea height *follows on a lag* while the water is already visibly
 *   windy: whitecap coverage answers the wind at once, the height does not.
 * - **dying** — a mature 12.5 m/s sea, and the wind leaves it. The gate is that
 *   the sea outlives the wind by a long way.
 *
 * The present wind is **scripted, not generated.** `WeatherField` has its own
 * committed trace (`series-baseline.json`) and its own gates; putting it in
 * this loop as well would make every number here a function of two things at
 * once and neither gate would say anything clean. What is under test here is
 * the memory, and a memory is tested by handing it a known input.
 *
 * THE GATES, AND WHY EACH ONE IS THE ONE THAT MATTERS
 * ---------------------------------------------------
 * - `remoteSwellIdentical` — **bit-identical**, by `Object.is`, on every swell
 *   number in every sample of both runs. Weather never writes remote swell;
 *   this is that sentence as an assertion rather than as an intention.
 * - `maxProbeStepPerCeiling`, against the **uncoupled control's own figure for
 *   the same script** — the wave phase is continuous across every transition. A
 *   phase reset does not produce a small error, it produces a metre-scale jump
 *   in the water under the ship, so a probe of the actual surface height is a
 *   better instrument than any comparison of phase registers: it is the thing a
 *   player would see. The control is the same run with `Independent` coupling,
 *   which never transitions at all, so it measures exactly what ordinary
 *   Gerstner motion looks like through the same probes and the coupled run is
 *   held to it.
 * - `foamHistoryPreserved` — the four things that would erase the persistent
 *   foam field: a snapped command (`set(state, 0)` leaves the controller
 *   untransitioning and `WaveField` un-reapplied), a changed seed (every
 *   component redrawn), a changed foam persistence or generation, or a shift in
 *   the parameter-space registration the foam is indexed in. The coupling is
 *   required to touch none of them.
 * - `windSeaHsLagSeconds` — the deliverable, in seconds. How long after the
 *   wind arrives at its new value the sea is halfway to the height that wind
 *   implies.
 */

import { findSeaState } from './presets';
import {
  cloneSeaState,
  type SeaState,
  type SwellParams,
} from './seaState';
import {
  effectiveGrowthWind,
  whitecapCoverage,
  windSeaFromWind,
} from './spectrum';
import { SeaStateController } from './SeaStateController';
import {
  WIND_SEA_COMMAND_DEADBAND,
  WIND_SEA_COMMAND_SECONDS,
  WIND_SEA_MEMORY,
  WindSeaCoupling,
  windSeaResponseSeconds,
  type PresentWind,
} from './WindSeaMemory';
import { DEFAULT_WORLD_SECONDS_PER_REAL_SECOND } from '../world/clock';
import { WaveField } from '../scene/Waves';

/** Presentation seconds per step. A plausible frame, and a tight probe. */
const STEP_SECONDS = 0.05;

/** Where the surface is probed for continuity, metres in the wave frame. */
const PROBES: ReadonlyArray<readonly [number, number]> = [
  [0, 0],
  [37, -19],
  [-104, 61],
  [220, 143],
];

/** How often a row is written to the committed file, presentation seconds. */
const SAMPLE_INTERVAL_SECONDS = 10;

export const WIND_SEA_EVIDENCE_CONTRACT = Object.freeze({
  stepSeconds: STEP_SECONDS,
  sampleIntervalSeconds: SAMPLE_INTERVAL_SECONDS,
  /**
   * The astronomical calendar, which is the clock the memory relaxes on
   * (decision D1). Read from `src/world/clock.ts` rather than restated: 30
   * world seconds per real second, so a world hour is two real minutes.
   */
  worldSecondsPerRealSecond: DEFAULT_WORLD_SECONDS_PER_REAL_SECOND,
  weatherRate: 1,
  probes: PROBES.map(([x, z]) => ({ x, z })),
  memory: WIND_SEA_MEMORY,
  commandDeadband: WIND_SEA_COMMAND_DEADBAND,
  commandSeconds: WIND_SEA_COMMAND_SECONDS,
  conventions:
    'wind speeds m/s; directionDeg is the compass heading the wind blows ' +
    'toward, matching WorldWind and the sea state; times are presentation ' +
    'seconds unless a field says world',
} as const);

export interface WindSeaScriptSegment {
  /** Presentation seconds at which this segment ends. */
  untilSeconds: number;
  speedMps: number;
  directionDeg: number;
}

export interface WindSeaScript {
  name: string;
  seaStateName: string;
  description: string;
  durationSeconds: number;
  /** Linear ramps between the endpoints below; the first is the start. */
  segments: readonly WindSeaScriptSegment[];
}

/**
 * The freshening. Two real minutes of settled weather first, deliberately: a
 * trace that starts moving on step one cannot show that a steady wind leaves
 * the sea alone, which is half of what makes this safe to ship.
 */
export const FRESHENING_SCRIPT: WindSeaScript = {
  name: 'freshening',
  seaStateName: 'CURRENT_MODERATE',
  description:
    'The production sea at 6 m/s. After two settled minutes the wind gets up ' +
    'to 14 m/s over five, veering 26 degrees with it, then holds.',
  durationSeconds: 1800,
  segments: [
    { untilSeconds: 0, speedMps: 6.0, directionDeg: 144 },
    { untilSeconds: 120, speedMps: 6.0, directionDeg: 144 },
    { untilSeconds: 420, speedMps: 14.0, directionDeg: 170 },
    { untilSeconds: 1800, speedMps: 14.0, directionDeg: 170 },
  ],
};

/** The dying wind. A mature 12.5 m/s sea, and the wind walks away from it. */
export const DYING_SCRIPT: WindSeaScript = {
  name: 'dying',
  seaStateName: 'MATURE_WIND_SEA',
  description:
    'A developed 12.5 m/s sea. After two settled minutes the wind falls away ' +
    'to 4 m/s over five, then holds. The sea has to outlive it.',
  durationSeconds: 1800,
  segments: [
    { untilSeconds: 0, speedMps: 12.5, directionDeg: 72 },
    { untilSeconds: 120, speedMps: 12.5, directionDeg: 72 },
    { untilSeconds: 420, speedMps: 4.0, directionDeg: 72 },
    { untilSeconds: 1800, speedMps: 4.0, directionDeg: 72 },
  ],
};

export interface WindSeaTraceSample {
  seconds: number;
  worldHours: number;
  /** The wind now, as the weather system would publish it. */
  presentWindMps: number;
  presentWindDirectionDeg: number;
  /** The sea's record: the wind working on it, and how far it has developed. */
  seaWindMps: number;
  seaWindDirectionDeg: number;
  seaMaturity: number;
  /** The memory itself — the wind this sea's height belongs to. */
  developedWindMps: number;
  /** Significant height of the wind sea alone, metres. */
  windSeaHsM: number;
  /** What that height would be if the sea answered the wind instantly. */
  equilibriumWindSeaHsM: number;
  /** Peak period of the wind sea, seconds. Shortens as the wind freshens. */
  windSeaPeakPeriodS: number;
  /** Monahan far-field whitecap fraction, from the sea's own record. */
  whitecapCoverage: number;
  /** Significant height of the whole resolved sea, metres. */
  resolvedSignificantHeightM: number;
  /** Largest probe elevation change since the previous *step*, metres. */
  maxProbeElevationStepM: number;
}

export interface WindSeaRunEvidence {
  name: string;
  seaStateName: string;
  description: string;
  script: readonly WindSeaScriptSegment[];
  base: {
    windMps: number;
    windDirectionDeg: number;
    maturity: number;
    windSeaHsM: number;
    seed: number;
  };
  response: {
    /** Time constant at the run's working wind, world seconds and real. */
    tauWorldSeconds: number;
    tauRealSeconds: number;
    /**
     * Seconds after the wind reached its new value before the wind sea was
     * halfway from its old height to the new equilibrium. The lag, in one
     * number — and `null` for the uncoupled controls, whose sea never moves
     * and therefore never gets halfway anywhere. JSON has no NaN, so the
     * absence has to be a value the rebuild produces too.
     */
    windSeaHsLagSeconds: number | null;
    /** Fraction of the height change already done when the wind arrived. */
    hsFractionAtWindArrival: number;
    /** The wind sea's height at that instant, metres. */
    windSeaHsAtWindArrivalM: number;
    /**
     * And that height as a multiple of the height the wind then implied. Under
     * 1 means the sea has not caught up; over 1 means it has not let go. It is
     * the whole round in one number, and it points opposite ways in the two
     * runs, which is the point.
     */
    hsMultipleOfEquilibriumAtWindArrival: number;
    /** Fraction of the *whitecap* change already done at the same instant. */
    whitecapFractionAtWindArrival: number;
    windArrivalSeconds: number;
    startWindSeaHsM: number;
    endWindSeaHsM: number;
    equilibriumWindSeaHsM: number;
  };
  gates: {
    remoteSwellIdentical: boolean;
    foamHistoryPreserved: boolean;
    minCommandSeconds: number;
    commandsIssued: number;
    settledCommandsBeforeTheWindMoved: number;
    maxProbeElevationStepM: number;
    /**
     * The same measurement made dimensionless: the worst probe step divided by
     * that step's own `Σ|aᵢωᵢ|·dt`. Comparable across a calm and a gale, and
     * comparable against the uncoupled control run, which is what makes it a
     * gate rather than a number.
     */
    maxProbeStepPerCeiling: number;
    seedChanged: boolean;
    whitewaterChanged: boolean;
  };
  trace: WindSeaTraceSample[];
}

export interface WindSeaEvidence {
  contract: typeof WIND_SEA_EVIDENCE_CONTRACT;
  runs: WindSeaRunEvidence[];
  /** The same scripts with `Independent` coupling. See `buildWindSeaEvidence`. */
  controls: WindSeaRunEvidence[];
}

/** Storage rounding, shared with the recompute test for exact comparison. */
export function roundWindSeaValue(value: number): number {
  return Math.round(value * 1e6) / 1e6 + 0;
}

function scriptedWind(script: WindSeaScript, seconds: number): PresentWind {
  const segments = script.segments;
  for (let i = 1; i < segments.length; i++) {
    const from = segments[i - 1];
    const to = segments[i];
    if (seconds <= to.untilSeconds) {
      const span = to.untilSeconds - from.untilSeconds;
      const t = span <= 0 ? 1 : (seconds - from.untilSeconds) / span;
      return {
        speedMps: from.speedMps + (to.speedMps - from.speedMps) * t,
        directionDeg:
          from.directionDeg + (to.directionDeg - from.directionDeg) * t,
        gustiness: 0,
      };
    }
  }
  const last = segments[segments.length - 1];
  return {
    speedMps: last.speedMps,
    directionDeg: last.directionDeg,
    gustiness: 0,
  };
}

/** The instant the wind stopped changing — the ramp's end. */
function windArrivalSeconds(script: WindSeaScript): number {
  const segments = script.segments;
  for (let i = segments.length - 1; i > 0; i--) {
    if (
      segments[i].speedMps !== segments[i - 1].speedMps ||
      segments[i].directionDeg !== segments[i - 1].directionDeg
    ) {
      return segments[i].untilSeconds;
    }
  }
  return 0;
}

function swellIdentical(a: SwellParams, b: SwellParams): boolean {
  return (
    a.enabled === b.enabled &&
    Object.is(a.significantHeight, b.significantHeight) &&
    Object.is(a.peakPeriod, b.peakPeriod) &&
    Object.is(a.directionDeg, b.directionDeg) &&
    Object.is(a.spreadDeg, b.spreadDeg) &&
    Object.is(a.steepness, b.steepness) &&
    Object.is(a.groupiness, b.groupiness)
  );
}

function whitewaterIdentical(a: SeaState, b: SeaState): boolean {
  return (
    Object.is(a.whitewater.generation, b.whitewater.generation) &&
    Object.is(a.whitewater.persistenceSeconds, b.whitewater.persistenceSeconds) &&
    Object.is(a.whitewater.breakup, b.whitewater.breakup) &&
    Object.is(a.whitewater.windAdvection, b.whitewater.windAdvection) &&
    Object.is(a.whitewater.sprayIntensity, b.whitewater.sprayIntensity) &&
    Object.is(a.whitewater.thresholdBias, b.whitewater.thresholdBias)
  );
}

/** Wind-sea significant height and peak period from a sea state's own record. */
function windSeaOf(state: SeaState): {
  significantHeight: number;
  peakPeriod: number;
} {
  const growth = effectiveGrowthWind(state.generatingWind.speedMps);
  const sea = windSeaFromWind(growth, state.generatingWind.maturity);
  return {
    significantHeight: sea.significantHeight,
    peakPeriod: sea.peakPeriod,
  };
}

export function buildWindSeaRunEvidence(
  script: WindSeaScript,
  coupled = true,
): WindSeaRunEvidence {
  const base = cloneSeaState(findSeaState(script.seaStateName));
  const seaStates = new SeaStateController(base);
  const waves = new WaveField(base);
  const coupling = new WindSeaCoupling(seaStates, base, coupled);

  // Every `set` the coupling issues, recorded so the gate can see that none of
  // them snapped. A snap is what would leave the foam field stranded.
  const commandSeconds: number[] = [];
  const nativeSet = seaStates.set.bind(seaStates);
  (seaStates as { set: SeaStateController['set'] }).set = (next, seconds) => {
    commandSeconds.push(seconds);
    nativeSet(next, seconds);
  };

  const arrival = windArrivalSeconds(script);
  const steps = Math.round(script.durationSeconds / STEP_SECONDS);
  const sampleEvery = Math.round(SAMPLE_INTERVAL_SECONDS / STEP_SECONDS);

  let weatherSeconds = 0;
  let remoteSwellIdentical = true;
  let seedChanged = false;
  let whitewaterChanged = false;
  let maxProbeStep = 0;
  let maxProbeStepPerCeiling = 0;
  let commandsBeforeTheWindMoved = 0;
  let hsAtArrival = Number.NaN;
  let whitecapAtArrival = Number.NaN;
  let halfwaySeconds = Number.NaN;

  const startWindSea = windSeaOf(base);
  const finalWind = scriptedWind(script, script.durationSeconds);
  const equilibrium = windSeaFromWind(
    effectiveGrowthWind(finalWind.speedMps),
    base.generatingWind.maturity,
  ).significantHeight;
  const halfway =
    startWindSea.significantHeight +
    0.5 * (equilibrium - startWindSea.significantHeight);
  const startWhitecap = whitecapCoverage(base.generatingWind.speedMps);
  const endWhitecap = whitecapCoverage(finalWind.speedMps);

  const previousProbes = PROBES.map(([x, z]) => waves.sampleHeight(x, z));
  const trace: WindSeaTraceSample[] = [];

  for (let i = 1; i <= steps; i++) {
    const seconds = i * STEP_SECONDS;
    weatherSeconds +=
      STEP_SECONDS *
      WIND_SEA_EVIDENCE_CONTRACT.worldSecondsPerRealSecond *
      WIND_SEA_EVIDENCE_CONTRACT.weatherRate;
    const present = scriptedWind(script, seconds);

    const commandsBefore = coupling.commandsIssued;
    coupling.update(STEP_SECONDS, weatherSeconds, present);
    if (seconds <= 120 && coupling.commandsIssued > commandsBefore) {
      commandsBeforeTheWindMoved += coupling.commandsIssued - commandsBefore;
    }

    // Exactly the production order: resolve the sea, re-apply it continuously
    // when it moved, then advance wave time and look at the water.
    if (seaStates.advance(STEP_SECONDS)) {
      waves.applySeaState(seaStates.state, true);
    }
    waves.setTime(seconds);

    const state = seaStates.state;
    if (!swellIdentical(state.primary, base.primary)) remoteSwellIdentical = false;
    if (!swellIdentical(state.secondary, base.secondary)) {
      remoteSwellIdentical = false;
    }
    if (!Object.is(state.seed, base.seed)) seedChanged = true;
    if (!whitewaterIdentical(state, base)) whitewaterChanged = true;

    let stepMax = 0;
    for (let p = 0; p < PROBES.length; p++) {
      const height = waves.sampleHeight(PROBES[p][0], PROBES[p][1]);
      stepMax = Math.max(stepMax, Math.abs(height - previousProbes[p]));
      previousProbes[p] = height;
    }
    maxProbeStep = Math.max(maxProbeStep, stepMax);
    // Normalised by THIS step's own ceiling, because the sea's size changes
    // through the run and an absolute metre figure would be comparing a gale
    // with a calm. See `verticalRateCeilingMps`.
    const ceiling = verticalRateCeilingMps(waves) * STEP_SECONDS;
    if (ceiling > 0) {
      maxProbeStepPerCeiling = Math.max(maxProbeStepPerCeiling, stepMax / ceiling);
    }

    const windSea = windSeaOf(state);
    const coverage = whitecapCoverage(state.generatingWind.speedMps);

    if (Number.isNaN(hsAtArrival) && seconds >= arrival) {
      hsAtArrival = windSea.significantHeight;
      whitecapAtArrival = coverage;
    }
    if (
      Number.isNaN(halfwaySeconds) &&
      seconds > 0 &&
      (equilibrium >= startWindSea.significantHeight
        ? windSea.significantHeight >= halfway
        : windSea.significantHeight <= halfway)
    ) {
      halfwaySeconds = seconds;
    }

    if (i % sampleEvery === 0) {
      trace.push({
        seconds: roundWindSeaValue(seconds),
        worldHours: roundWindSeaValue(weatherSeconds / 3600),
        presentWindMps: roundWindSeaValue(present.speedMps),
        presentWindDirectionDeg: roundWindSeaValue(present.directionDeg),
        seaWindMps: roundWindSeaValue(state.generatingWind.speedMps),
        seaWindDirectionDeg: roundWindSeaValue(state.generatingWind.directionDeg),
        seaMaturity: roundWindSeaValue(state.generatingWind.maturity),
        developedWindMps: roundWindSeaValue(coupling.developedWind.speedMps),
        windSeaHsM: roundWindSeaValue(windSea.significantHeight),
        equilibriumWindSeaHsM: roundWindSeaValue(
          windSeaFromWind(
            effectiveGrowthWind(present.speedMps),
            base.generatingWind.maturity,
          ).significantHeight,
        ),
        windSeaPeakPeriodS: roundWindSeaValue(windSea.peakPeriod),
        whitecapCoverage: roundWindSeaValue(coverage),
        resolvedSignificantHeightM: roundWindSeaValue(waves.significantHeight),
        maxProbeElevationStepM: roundWindSeaValue(stepMax),
      });
    }
  }

  const working = Math.max(
    Math.abs(finalWind.speedMps),
    base.generatingWind.speedMps,
  );
  const dying = finalWind.speedMps < base.generatingWind.speedMps;
  const tauWorld = windSeaResponseSeconds(working, dying);

  return {
    name: script.name,
    seaStateName: script.seaStateName,
    description: script.description,
    script: script.segments,
    base: {
      windMps: base.generatingWind.speedMps,
      windDirectionDeg: base.generatingWind.directionDeg,
      maturity: base.generatingWind.maturity,
      windSeaHsM: roundWindSeaValue(startWindSea.significantHeight),
      seed: base.seed,
    },
    response: {
      tauWorldSeconds: roundWindSeaValue(tauWorld),
      tauRealSeconds: roundWindSeaValue(
        tauWorld / WIND_SEA_EVIDENCE_CONTRACT.worldSecondsPerRealSecond,
      ),
      windSeaHsLagSeconds: Number.isFinite(halfwaySeconds)
        ? roundWindSeaValue(halfwaySeconds - arrival)
        : null,
      hsFractionAtWindArrival: roundWindSeaValue(
        fraction(startWindSea.significantHeight, equilibrium, hsAtArrival),
      ),
      windSeaHsAtWindArrivalM: roundWindSeaValue(hsAtArrival),
      hsMultipleOfEquilibriumAtWindArrival: roundWindSeaValue(
        equilibrium > 0 ? hsAtArrival / equilibrium : 0,
      ),
      whitecapFractionAtWindArrival: roundWindSeaValue(
        fraction(startWhitecap, endWhitecap, whitecapAtArrival),
      ),
      windArrivalSeconds: arrival,
      startWindSeaHsM: roundWindSeaValue(startWindSea.significantHeight),
      endWindSeaHsM: roundWindSeaValue(
        windSeaOf(seaStates.state).significantHeight,
      ),
      equilibriumWindSeaHsM: roundWindSeaValue(equilibrium),
    },
    gates: {
      remoteSwellIdentical,
      foamHistoryPreserved:
        !seedChanged &&
        !whitewaterChanged &&
        commandSeconds.every((seconds) => seconds > 0),
      minCommandSeconds: roundWindSeaValue(
        commandSeconds.length > 0 ? Math.min(...commandSeconds) : 0,
      ),
      commandsIssued: coupling.commandsIssued,
      settledCommandsBeforeTheWindMoved: commandsBeforeTheWindMoved,
      maxProbeElevationStepM: roundWindSeaValue(maxProbeStep),
      maxProbeStepPerCeiling: roundWindSeaValue(maxProbeStepPerCeiling),
      seedChanged,
      whitewaterChanged,
    },
    trace,
  };
}

function fraction(from: number, to: number, at: number): number {
  const span = to - from;
  return Math.abs(span) < 1e-12 ? 1 : (at - from) / span;
}

/**
 * `Σ aᵢ ωᵢ` over the live components — the fastest the *Lagrangian* surface can
 * move, and therefore a scale rather than a hard bound: these are Gerstner
 * waves, so a probe held at a fixed world point sees a steep crest sweep past
 * faster than that, by a factor that grows with the crest sharpness. Which is
 * exactly why the gate compares the coupled run's ratio against the SAME ratio
 * from an uncoupled control over the same script, rather than against 1.
 */
function verticalRateCeilingMps(waves: WaveField): number {
  let sum = 0;
  for (let i = 0; i < waves.count; i++) {
    const amplitude = waves.waveA[i * 4 + 2];
    const k = waves.waveA[i * 4 + 3];
    // Deep-water dispersion, the same relation `spectrum.ts` builds ω from.
    sum += Math.abs(amplitude) * Math.sqrt(9.81 * Math.abs(k));
  }
  return sum * waves.amplitude;
}

export function buildWindSeaEvidence(): WindSeaEvidence {
  return {
    contract: WIND_SEA_EVIDENCE_CONTRACT,
    runs: [
      buildWindSeaRunEvidence(FRESHENING_SCRIPT),
      buildWindSeaRunEvidence(DYING_SCRIPT),
    ],
    // The `Independent` half of decision D5, doing double duty as the phase
    // control. The same two scripts with the coupling switched off: the sea
    // never moves, so no transition ever runs, so whatever the probes see is
    // ordinary Gerstner motion and nothing else. The coupled runs' probe ratios
    // are gated against these.
    controls: [
      buildWindSeaRunEvidence(FRESHENING_SCRIPT, false),
      buildWindSeaRunEvidence(DYING_SCRIPT, false),
    ],
  };
}

/**
 * Physical gates, shared verbatim by the exporter and the test suite.
 * Throws with a specific message on the first violated gate.
 */
export function validateWindSeaEvidence(evidence: WindSeaEvidence): void {
  if (evidence.runs.length !== 2) {
    throw new Error(`expected the freshening and dying runs, got ${evidence.runs.length}`);
  }
  const [freshening, dying] = evidence.runs;
  if (evidence.controls.length !== evidence.runs.length) {
    throw new Error('every run needs its uncoupled control');
  }

  // PHASE CONTINUITY. The control ran the same script with the sea uncoupled,
  // so it never transitioned at all and its worst probe step is pure Gerstner
  // motion. The coupled run transitions continuously; if its phase were being
  // reset the water would jump by a wave height, which against this ratio is
  // two orders of magnitude, not fifteen per cent.
  for (const [index, run] of evidence.runs.entries()) {
    const control = evidence.controls[index];
    if (control.gates.commandsIssued !== 0) {
      throw new Error(
        `${control.name} control: an uncoupled sea commanded ` +
          `${control.gates.commandsIssued} times. Independent must mean ` +
          'independent — that is decision D5 and it is a switch a lab session ' +
          'has to be able to trust.',
      );
    }
    const allowance = control.gates.maxProbeStepPerCeiling * 1.25 + 0.02;
    if (run.gates.maxProbeStepPerCeiling > allowance) {
      throw new Error(
        `${run.name}: the water moved ${run.gates.maxProbeStepPerCeiling} of its ` +
          'own vertical-rate scale in one step, against ' +
          `${control.gates.maxProbeStepPerCeiling} for the same script with the ` +
          'sea never changing. The wave phase is not continuous across the ' +
          'transition.',
      );
    }
  }

  for (const run of evidence.runs) {
    if (!run.gates.remoteSwellIdentical) {
      throw new Error(
        `${run.name}: weather moved the remote swell. It must never write it — ` +
          'a swell from a storm two thousand kilometres away does not answer ' +
          'the local breeze.',
      );
    }
    if (!run.gates.foamHistoryPreserved) {
      throw new Error(
        `${run.name}: the persistent foam field would have been erased — ` +
          `seedChanged=${run.gates.seedChanged}, ` +
          `whitewaterChanged=${run.gates.whitewaterChanged}, ` +
          `minCommandSeconds=${run.gates.minCommandSeconds}`,
      );
    }
    if (run.gates.settledCommandsBeforeTheWindMoved !== 0) {
      throw new Error(
        `${run.name}: the coupling commanded the sea ` +
          `${run.gates.settledCommandsBeforeTheWindMoved} times while the wind ` +
          'was steady. A settled spell must cost nothing and move nothing.',
      );
    }
    if (run.gates.commandsIssued < 1) {
      throw new Error(`${run.name}: the coupling never commanded the sea at all`);
    }
    for (const [index, sample] of run.trace.entries()) {
      const numbers = Object.values(sample);
      if (numbers.some((value) => !Number.isFinite(value))) {
        throw new Error(`${run.name}: sample ${index} contains a non-finite value`);
      }
    }
    for (const [key, value] of Object.entries(run.response)) {
      if (value !== null && !Number.isFinite(value)) {
        throw new Error(`${run.name}: response.${key} is ${value}`);
      }
    }
  }

  // THE FRESHENING GATE. The wind arrives; the sea does not.
  if (!(freshening.response.hsFractionAtWindArrival < 0.75)) {
    throw new Error(
      'freshening: the wind sea was ' +
        `${(freshening.response.hsFractionAtWindArrival * 100).toFixed(0)}% of the ` +
        'way to its new height the moment the wind arrived. There is no memory ' +
        'here — the sea is answering the wind instantly, which is the state WX2 ' +
        'exists to leave.',
    );
  }
  if (!((freshening.response.windSeaHsLagSeconds ?? 0) > 60)) {
    throw new Error(
      `freshening: the sea was halfway there only ` +
        `${freshening.response.windSeaHsLagSeconds} s after the wind arrived; ` +
        'that is not a lag anybody can watch',
    );
  }
  // WINDY BEFORE BIG. The whitecaps must be much further along than the height.
  if (
    !(
      freshening.response.whitecapFractionAtWindArrival >
      freshening.response.hsFractionAtWindArrival + 0.2
    )
  ) {
    throw new Error(
      'freshening: the whitecaps are no further ahead of the height than the ' +
        'height itself — the water is not getting windy before it gets big ' +
        `(whitecap ${freshening.response.whitecapFractionAtWindArrival}, ` +
        `height ${freshening.response.hsFractionAtWindArrival})`,
    );
  }
  if (!(freshening.response.endWindSeaHsM > freshening.base.windSeaHsM)) {
    throw new Error('freshening: the sea never built at all');
  }
  if (!(freshening.response.hsMultipleOfEquilibriumAtWindArrival < 0.5)) {
    throw new Error(
      'freshening: when the wind reached its new strength the sea was already ' +
        `${freshening.response.hsMultipleOfEquilibriumAtWindArrival}× the height ` +
        'that wind implies. It should be well under half of it — the water has ' +
        'not had time.',
    );
  }

  // THE DYING GATE. The wind goes; the sea stays.
  if (!(dying.response.hsFractionAtWindArrival < 0.5)) {
    throw new Error(
      'dying: the sea had already lost ' +
        `${(dying.response.hsFractionAtWindArrival * 100).toFixed(0)}% of its ` +
        'height by the time the wind had finished dropping. It is supposed to ' +
        'outlive the wind.',
    );
  }
  if (!(dying.response.hsMultipleOfEquilibriumAtWindArrival > 2)) {
    throw new Error(
      'dying: when the wind had finished dropping the sea was only ' +
        `${dying.response.hsMultipleOfEquilibriumAtWindArrival}× the height that ` +
        'wind implies. It is supposed to be several times it — that is what ' +
        '"the sea stays up" means, and it is the half of the accept-when this ' +
        'run exists for.',
    );
  }
  if (!((dying.response.windSeaHsLagSeconds ?? 0) > 60)) {
    throw new Error(
      `dying: the sea was halfway down only ${dying.response.windSeaHsLagSeconds} s ` +
        'after the wind had gone',
    );
  }
  if (!(dying.response.endWindSeaHsM < dying.base.windSeaHsM)) {
    throw new Error('dying: the sea never went down at all');
  }
}
