/**
 * Deterministic gust-trace evidence for the world wind.
 *
 * Regenerated by `npm run wind:baseline` into
 * `evidence/world-wind/gust-baseline.json`. One `WorldWind` instance per
 * non-debug sea preset, all sharing the fixed default seed, advanced at an
 * exact 60 Hz for ten minutes. The committed record is the proof that the gust
 * process is reproducible, bounded by its stated amplitudes, and mean-reverting
 * on the stated timescale — and `tests/world-wind.test.ts` recomputes a preset
 * from scratch and requires exact equality, so the trace cannot drift from the
 * code that claims to produce it.
 */

import { findSeaState, REGRESSION_ORDER } from '../ocean/presets';
import {
  DIRECTION_WANDER_DEG,
  SPEED_GUST_AMPLITUDE_FRACTION,
  WORLD_WIND_DEFAULT_SEED,
  WorldWind,
} from './WorldWind';

export const WORLD_WIND_EVIDENCE_CONTRACT = Object.freeze({
  seed: WORLD_WIND_DEFAULT_SEED,
  sampleHz: 60,
  durationSeconds: 600,
  traceSeconds: 60,
  traceIntervalSeconds: 0.25,
  speedGustAmplitudeFraction: SPEED_GUST_AMPLITUDE_FRACTION,
  directionWanderDeg: DIRECTION_WANDER_DEG,
  convention:
    'directionDeg is the compass heading the wind blows toward, ' +
    'matching sea-state directions',
} as const);

export interface WorldWindTraceSample {
  timeSeconds: number;
  instantaneousSpeedMps: number;
  instantaneousDirectionTowardDeg: number;
  gustSpeedFraction: number;
}

export interface WorldWindPresetEvidence {
  name: string;
  label: string;
  meanSpeedMps: number;
  meanDirectionTowardDeg: number;
  gustiness: number;
  stats: {
    meanInstantaneousSpeedMps: number;
    minInstantaneousSpeedMps: number;
    maxInstantaneousSpeedMps: number;
    speedFluctuationStdMps: number;
    maxAbsDirectionOffsetDeg: number;
    directionOffsetStdDeg: number;
    meanGustZeroCrossingIntervalSeconds: number;
  };
  trace: WorldWindTraceSample[];
}

export interface WorldWindEvidence {
  contract: typeof WORLD_WIND_EVIDENCE_CONTRACT;
  presets: WorldWindPresetEvidence[];
}

/** Storage rounding, shared with the recompute test for exact comparison. */
export function roundWindValue(value: number): number {
  return Math.round(value * 1e6) / 1e6;
}

/** The ten non-debug presets, in the buoyancy-regression order. */
export function worldWindEvidencePresetNames(): string[] {
  return REGRESSION_ORDER.filter((name) => name !== 'EXTREME_DEBUG');
}

export function buildWorldWindPresetEvidence(
  presetName: string,
): WorldWindPresetEvidence {
  const contract = WORLD_WIND_EVIDENCE_CONTRACT;
  const preset = findSeaState(presetName);
  if (preset.name !== presetName) {
    throw new Error(`unknown sea preset ${presetName}`);
  }
  const wind = new WorldWind(contract.seed);
  wind.setMean(
    preset.generatingWind.speedMps,
    preset.generatingWind.directionDeg,
    preset.generatingWind.gustiness,
  );

  const dt = 1 / contract.sampleHz;
  const steps = contract.durationSeconds * contract.sampleHz;
  const traceEvery = Math.round(contract.traceIntervalSeconds * contract.sampleHz);

  const trace: WorldWindTraceSample[] = [];
  let speedSum = 0;
  let speedSquaredSum = 0;
  let minSpeed = Number.POSITIVE_INFINITY;
  let maxSpeed = Number.NEGATIVE_INFINITY;
  let offsetSquaredSum = 0;
  let maxAbsOffset = 0;
  let crossings = 0;
  let previousFractionPositive: boolean | null = null;

  for (let i = 1; i <= steps; i++) {
    wind.advance(dt);
    const speed = wind.instantaneousSpeedMps;
    const offset = wind.gustDirectionOffsetDeg;
    const fraction = wind.gustSpeedFraction;

    speedSum += speed;
    speedSquaredSum += speed * speed;
    minSpeed = Math.min(minSpeed, speed);
    maxSpeed = Math.max(maxSpeed, speed);
    offsetSquaredSum += offset * offset;
    maxAbsOffset = Math.max(maxAbsOffset, Math.abs(offset));

    const positive = fraction >= 0;
    if (previousFractionPositive !== null && positive !== previousFractionPositive) {
      crossings += 1;
    }
    previousFractionPositive = positive;

    if (i % traceEvery === 0 && i * dt <= contract.traceSeconds + 1e-9) {
      trace.push({
        timeSeconds: roundWindValue(i * dt),
        instantaneousSpeedMps: roundWindValue(speed),
        instantaneousDirectionTowardDeg: roundWindValue(
          wind.instantaneousDirectionTowardDeg,
        ),
        gustSpeedFraction: roundWindValue(fraction),
      });
    }
  }

  const meanSpeed = speedSum / steps;
  const speedVariance = Math.max(0, speedSquaredSum / steps - meanSpeed * meanSpeed);

  return {
    name: preset.name,
    label: preset.label,
    meanSpeedMps: preset.generatingWind.speedMps,
    meanDirectionTowardDeg: preset.generatingWind.directionDeg,
    gustiness: preset.generatingWind.gustiness,
    stats: {
      meanInstantaneousSpeedMps: roundWindValue(meanSpeed),
      minInstantaneousSpeedMps: roundWindValue(minSpeed),
      maxInstantaneousSpeedMps: roundWindValue(maxSpeed),
      speedFluctuationStdMps: roundWindValue(Math.sqrt(speedVariance)),
      maxAbsDirectionOffsetDeg: roundWindValue(maxAbsOffset),
      directionOffsetStdDeg: roundWindValue(
        Math.sqrt(offsetSquaredSum / steps),
      ),
      meanGustZeroCrossingIntervalSeconds: roundWindValue(
        contract.durationSeconds / Math.max(1, crossings),
      ),
    },
    trace,
  };
}

export function buildWorldWindEvidence(): WorldWindEvidence {
  return {
    contract: WORLD_WIND_EVIDENCE_CONTRACT,
    presets: worldWindEvidencePresetNames().map(buildWorldWindPresetEvidence),
  };
}

/**
 * Physical gates, shared verbatim by the exporter and the test suite.
 * Throws with a specific message on the first violated gate.
 */
export function validateWorldWindEvidence(evidence: WorldWindEvidence): void {
  const contract = evidence.contract;
  const expectedNames = worldWindEvidencePresetNames();
  const actualNames = evidence.presets.map((preset) => preset.name);
  if (actualNames.join(',') !== expectedNames.join(',')) {
    throw new Error(
      `evidence presets [${actualNames}] do not match the non-debug set [${expectedNames}]`,
    );
  }

  for (const preset of evidence.presets) {
    const { stats, trace } = preset;
    const peakSpeedExcursion =
      preset.meanSpeedMps *
      contract.speedGustAmplitudeFraction *
      preset.gustiness;
    const peakDirectionOffset = contract.directionWanderDeg * preset.gustiness;
    const slack = 1e-6;

    if (stats.minInstantaneousSpeedMps < 0) {
      throw new Error(`${preset.name}: instantaneous speed went negative`);
    }
    if (stats.maxInstantaneousSpeedMps > preset.meanSpeedMps + peakSpeedExcursion + slack) {
      throw new Error(
        `${preset.name}: speed exceeded the stated gust amplitude bound`,
      );
    }
    if (stats.minInstantaneousSpeedMps < preset.meanSpeedMps - peakSpeedExcursion - slack) {
      throw new Error(
        `${preset.name}: speed fell below the stated gust amplitude bound`,
      );
    }
    if (
      Math.abs(stats.meanInstantaneousSpeedMps - preset.meanSpeedMps) >
      0.03 * Math.max(preset.meanSpeedMps, 0.1)
    ) {
      throw new Error(
        `${preset.name}: ten-minute mean speed drifted more than 3% from the preset mean`,
      );
    }
    if (stats.maxAbsDirectionOffsetDeg > peakDirectionOffset + slack) {
      throw new Error(
        `${preset.name}: direction offset exceeded the stated wander bound`,
      );
    }
    if (preset.gustiness > 0 && preset.meanSpeedMps > 0) {
      const interval = stats.meanGustZeroCrossingIntervalSeconds;
      if (interval < 3 || interval > 60) {
        throw new Error(
          `${preset.name}: gust zero-crossing interval ${interval}s is outside the 3-60s character band`,
        );
      }
      if (stats.speedFluctuationStdMps <= 0) {
        throw new Error(`${preset.name}: gusty preset produced no speed fluctuation`);
      }
    }
    if (preset.gustiness === 0) {
      for (const sample of trace) {
        if (sample.instantaneousSpeedMps !== roundWindValue(preset.meanSpeedMps)) {
          throw new Error(
            `${preset.name}: zero gustiness must reproduce the mean exactly`,
          );
        }
        if (
          sample.instantaneousDirectionTowardDeg !==
          roundWindValue(preset.meanDirectionTowardDeg)
        ) {
          throw new Error(
            `${preset.name}: zero gustiness must not move the direction`,
          );
        }
      }
    }
    const numbers: number[] = [];
    for (const sample of trace) {
      numbers.push(
        sample.timeSeconds,
        sample.instantaneousSpeedMps,
        sample.instantaneousDirectionTowardDeg,
        sample.gustSpeedFraction,
      );
    }
    numbers.push(...Object.values(stats));
    if (numbers.some((value) => !Number.isFinite(value))) {
      throw new Error(`${preset.name}: evidence contains a non-finite value`);
    }
  }
}
